<script setup lang="ts">
/**
 * The clearance drawing (signature moment 4): one wheel in its wheel arch, seen from behind — what
 * you see standing behind the car looking at a rear wheel. Across is sideways, inside (the strut,
 * *Federbein*) on the left and outside (the fender, *Kotflügel*) on the right; up is height.
 *
 * - The tyre is a rounded shape as wide as its nominal section width and as high as the tyre; the
 *   rim inside it is as wide as the rim and as high as its diameter. Both wheels are drawn to one
 *   true scale, so a bigger tyre looks bigger.
 * - The mounting face (Anlagefläche, dash-dot) is the car's: one line for both wheels. A positive
 *   ET puts the rim's centre plane that far inboard of it; the tyre is centred on that plane.
 * - The strut and the fender are schematic (their place depends on the car) and the same for both.
 * - The current wheel is dashed, the new one solid and tinted.
 * - Two arrows under the wheels run from each current rim edge to the new one, exactly as long as
 *   the model's shift; an edge that moves by no whole millimetre has no arrow and reads
 *   *unverändert*.
 *
 * Everything is generated by `lib/felgenGeometry` (`rearScene`) from the same `FelgenModel` whose
 * texts are the labels (ACCURACY.md §6). The labels are HTML: the part names in a row above the
 * sheet, split between the strut and the fender; each arrow's label in a row of its own below it,
 * at the arrow's middle, shifted by the same fraction of its own width (`left: f; translateX(−f)`).
 * So a label stays inside the drawing's width, may wrap, and can never overlap another label or
 * the drawing, at any width. Ink and line colours only: nothing here is a verdict.
 *
 * A tyre and a rim that do not belong together (`implausible`) are not drawn at all — the results
 * say so in a sentence instead.
 *
 * Motion: when a value changes, the two wheels' numbers are tweened over `--d-2` with `--ease-std`
 * in a requestAnimationFrame loop and the scene is rebuilt from the in-between numbers. Labels and
 * the aria-label read the target values straight away. Under reduced motion, and on the server,
 * the drawing rests in its end state.
 */

import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import ValueText from './ValueText.vue'
import { felgenModel, REAR, rearFrame, rearScene, type RearFrame, type SetupSide, type WheelFrame, type WheelSetup } from '../../lib/felgenGeometry'
import { setupLine } from '../../lib/rechner'

const props = defineProps<{ current: WheelSetup; next: WheelSetup }>()

const model = computed(() => felgenModel(props.current, props.next))
const plausible = computed(() => model.value.implausible.length === 0)
const target = computed(() => rearFrame(model.value))

/* ── The morph ─────────────────────────────────────────────────────────────────── */

const SIDE_KEYS: SetupSide[] = ['current', 'next']
const FRAME_KEYS: (keyof WheelFrame)[] = ['centreX', 'tyreWidthMm', 'diameterMm', 'rimWidthMm', 'rimDiameterMm']

function cloneFrame(f: RearFrame): RearFrame {
    return { current: { ...f.current }, next: { ...f.next } }
}

function sameFrame(a: RearFrame, b: RearFrame): boolean {
    return SIDE_KEYS.every((side) => FRAME_KEYS.every((key) => a[side][key] === b[side][key]))
}

function lerpFrame(from: RearFrame, to: RearFrame, t: number): RearFrame {
    const out = cloneFrame(to)

    for (const side of SIDE_KEYS) {
        for (const key of FRAME_KEYS) {
            out[side][key] = from[side][key] + (to[side][key] - from[side][key]) * t
        }
    }

    return out
}

/** The CSS timing function as a number-to-number function (the usual Newton–Raphson on x). */
function cubicBezier(x1: number, y1: number, x2: number, y2: number): (t: number) => number {
    const a = (p1: number, p2: number) => 1 - 3 * p2 + 3 * p1
    const b = (p1: number, p2: number) => 3 * p2 - 6 * p1
    const c = (p1: number) => 3 * p1
    const at = (t: number, p1: number, p2: number) => ((a(p1, p2) * t + b(p1, p2)) * t + c(p1)) * t
    const slope = (t: number, p1: number, p2: number) => 3 * a(p1, p2) * t * t + 2 * b(p1, p2) * t + c(p1)

    return (x) => {
        if (x <= 0) {
            return 0
        }

        if (x >= 1) {
            return 1
        }

        let t = x

        for (let i = 0; i < 8; i++) {
            const dx = at(t, x1, x2) - x
            const d = slope(t, x1, x2)

            if (Math.abs(dx) < 1e-5 || d === 0) {
                break
            }

            t -= dx / d
        }

        return at(t, y1, y2)
    }
}

function parseMs(value: string): number | null {
    const match = /^\s*([\d.]+)\s*(ms|s)\s*$/.exec(value)

    if (match === null || match[1] === undefined) {
        return null
    }

    const n = Number(match[1])

    return Number.isFinite(n) ? (match[2] === 's' ? n * 1000 : n) : null
}

function parseBezier(value: string): ((t: number) => number) | null {
    const match = /cubic-bezier\(([^)]+)\)/.exec(value)
    const parts = match?.[1]?.split(',').map((v) => Number(v.trim())) ?? []

    if (parts.length !== 4 || parts.some((v) => !Number.isFinite(v))) {
        return null
    }

    return cubicBezier(parts[0] as number, parts[1] as number, parts[2] as number, parts[3] as number)
}

const frame = ref<RearFrame>(cloneFrame(target.value))
/* No motion until we are on a client that has not asked for stillness. */
const motion = ref(false)
let raf = 0
let duration = 200
let ease = cubicBezier(0.4, 0, 0.2, 1)

onMounted(() => {
    motion.value = !(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches ?? false)

    const style = getComputedStyle(document.documentElement)
    duration = parseMs(style.getPropertyValue('--d-2')) ?? duration
    ease = parseBezier(style.getPropertyValue('--ease-std')) ?? ease
})

function stop(): void {
    if (raf !== 0 && typeof cancelAnimationFrame === 'function') {
        cancelAnimationFrame(raf)
    }

    raf = 0
}

watch(target, (to) => {
    if (sameFrame(to, frame.value)) {
        return
    }

    stop()

    // Nothing to morph from or to while a comparison is not drawn: the drawing appears at rest.
    if (!motion.value || !plausible.value || typeof requestAnimationFrame !== 'function') {
        frame.value = cloneFrame(to)

        return
    }

    const from = cloneFrame(frame.value)
    const started = performance.now()

    const step = (now: number): void => {
        const t = Math.min(1, (now - started) / duration)
        frame.value = lerpFrame(from, to, ease(t))
        raf = t < 1 ? requestAnimationFrame(step) : 0
    }

    raf = requestAnimationFrame(step)
})

onBeforeUnmount(stop)

/* ── What is drawn (tweened) and what is written (the model, at once) ──────────── */

const scene = computed(() => rearScene(frame.value, model.value))
const resting = computed(() => rearScene(target.value, model.value))

function clampPercent(fraction: number): number {
    return Math.round(Math.min(Math.max(fraction, 0), 1) * 1000) / 10
}

/** `left: f; translateX(−f)` keeps a label inside its row with its anchor inside the label. */
function at(fraction: number): Record<string, string> {
    const f = clampPercent(fraction)

    return { left: `${f}%`, transform: `translateX(-${f}%)` }
}

/* The part names share one row, split halfway between the strut and the fender. */
const parts = computed(() => {
    const strut = resting.value.strut.anchor
    const fender = resting.value.fender.anchor
    const split = (strut + fender) / 2

    return {
        row: { gridTemplateColumns: `${clampPercent(split)}% minmax(0, 1fr)` },
        strut: at(strut / split),
        fender: at((fender - split) / (1 - split)),
    }
})

const labels = computed(() => ({
    outer: at(resting.value.outer.anchor),
    inner: at(resting.value.inner.anchor),
}))

const legend = computed(() => ({
    current: setupLine(props.current),
    next: setupLine(props.next),
}))

const description = computed(
    () =>
        `Blick von hinten auf ein Rad im Radhaus, rechnerisch. ${model.value.outer.text}. ${model.value.inner.text}. ` +
        'Federbein und Kotflügel schematisch.'
)
</script>

<template>
    <!-- One image to assistive tech (the sentence says what it shows); a figure may not carry role="img". -->
    <div v-if="plausible" class="cd" role="img" :aria-label="description">
        <div class="cd__stage">
            <p class="cd__view small">Blick von hinten auf ein Rad im Radhaus</p>
            <div class="cd__parts" :style="parts.row">
                <span class="cd__cell"><span class="cd__part micro" data-part="strut" :style="parts.strut">← innen · Federbein</span></span>
                <span class="cd__cell"><span class="cd__part micro" data-part="fender" :style="parts.fender">Kotflügel · außen →</span></span>
            </div>
            <p class="cd__note micro quiet">Federbein und Kotflügel: Lage schematisch – je nach Fahrzeug</p>

            <div class="cd__sheet">
                <svg
                    class="cd__svg"
                    :viewBox="`0 0 ${REAR.width} ${REAR.height}`"
                    :data-units-per-mm="scene.unitsPerMm"
                    aria-hidden="true"
                    focusable="false"
                >
                    <!-- The car: schematic, the same for both wheels. -->
                    <g class="cd__car">
                        <rect class="cd__line cd__schematic" data-part="strut" :x="scene.strut.tube.x" :y="scene.strut.tube.y" :width="scene.strut.tube.width" :height="scene.strut.tube.height" />
                        <path class="cd__line cd__spring" :d="scene.strut.spring" />
                        <path class="cd__line cd__schematic" data-part="fender" :d="scene.fender.path" />
                    </g>

                    <!-- The new wheel's tint first, so the current wheel's dashes stay visible across it. -->
                    <path class="cd__ring" :d="scene.next.ring" fill-rule="evenodd" />

                    <g class="old" data-wheel="current">
                        <rect class="cd__line cd__old cd__tyre" :x="scene.current.tyre.x" :y="scene.current.tyre.y" :width="scene.current.tyre.width" :height="scene.current.tyre.height" :rx="scene.current.tyre.r" />
                        <rect class="cd__line cd__old cd__rim" :x="scene.current.rim.x" :y="scene.current.rim.y" :width="scene.current.rim.width" :height="scene.current.rim.height" />
                    </g>
                    <g class="new" data-wheel="next">
                        <rect class="cd__line cd__new cd__tyre" :x="scene.next.tyre.x" :y="scene.next.tyre.y" :width="scene.next.tyre.width" :height="scene.next.tyre.height" :rx="scene.next.tyre.r" />
                        <rect class="cd__line cd__new cd__rim" :x="scene.next.rim.x" :y="scene.next.rim.y" :width="scene.next.rim.width" :height="scene.next.rim.height" />
                    </g>

                    <path class="cd__line cd__face" :d="scene.face" />

                    <path v-if="scene.outer.extFrom" class="cd__line cd__ext cd__ext--old" data-dim="outer" :d="scene.outer.extFrom" />
                    <path v-if="scene.outer.extTo" class="cd__line cd__ext" data-dim="outer" :d="scene.outer.extTo" />
                    <path v-if="scene.inner.extFrom" class="cd__line cd__ext cd__ext--old" data-dim="inner" :d="scene.inner.extFrom" />
                    <path v-if="scene.inner.extTo" class="cd__line cd__ext" data-dim="inner" :d="scene.inner.extTo" />
                    <path v-if="scene.outer.shaft" class="cd__line cd__dim" data-dim="outer" :d="scene.outer.shaft" />
                    <path v-if="scene.inner.shaft" class="cd__line cd__dim" data-dim="inner" :d="scene.inner.shaft" />
                    <path v-if="scene.outer.head" class="cd__head" data-dim="outer" :d="scene.outer.head" />
                    <path v-if="scene.inner.head" class="cd__head" data-dim="inner" :d="scene.inner.head" />
                </svg>
            </div>

            <div class="cd__row">
                <span class="cd__label micro" data-dim="outer" :style="labels.outer"><ValueText :text="model.outer.text" /></span>
            </div>
            <div class="cd__row">
                <span class="cd__label micro" data-dim="inner" :style="labels.inner"><ValueText :text="model.inner.text" /></span>
            </div>
        </div>

        <div class="cd__legend micro muted">
            <span class="cd__key" data-key="current">
                <svg class="cd__swatch" viewBox="0 0 32 8" width="32" height="8" aria-hidden="true" focusable="false">
                    <path class="cd__line cd__old" d="M0 4 H32" />
                </svg>
                <span>bisher <ValueText :text="legend.current" /></span>
            </span>
            <span class="cd__key" data-key="next">
                <svg class="cd__swatch" viewBox="0 0 32 8" width="32" height="8" aria-hidden="true" focusable="false">
                    <path class="cd__line cd__new" d="M0 4 H32" />
                </svg>
                <span>neu <ValueText :text="legend.next" /></span>
            </span>
            <span class="cd__key" data-key="face">
                <svg class="cd__swatch" viewBox="0 0 32 8" width="32" height="8" aria-hidden="true" focusable="false">
                    <path class="cd__line cd__face" d="M0 4 H32" />
                </svg>
                <span>Anlagefläche: hier wird die Felge angeschraubt</span>
            </span>
        </div>

        <p class="cd__caption micro quiet">Rad und Reifen maßstäblich, beide im selben Maßstab. Werte rechnerisch, auf ganze Millimeter gerundet.</p>
    </div>
</template>

<style scoped>
.cd {
    display: grid;
    gap: var(--sp-12);
    width: 100%;
    min-width: 0;
    margin: 0;
}

/* The sheet and its label rows share one width, so a label's fraction is the sheet's fraction. */
.cd__stage {
    display: grid;
    gap: var(--sp-4);
    width: 100%;
    max-width: 360px;
    min-width: 0;
}

/* The part names: one row, split halfway between strut and fender, so the two can never meet. */
.cd__parts {
    display: grid;
}

.cd__cell {
    position: relative;
    min-width: 0;
}

/* A label row: the label sits at its anchor and never leaves the row. */
.cd__row {
    position: relative;
    min-width: 0;
}

.cd__part,
.cd__label {
    position: relative;
    display: inline-block;
    max-width: 100%;
    color: var(--c-ink-2);
    font-weight: 500;
}

/* What the picture is, before anything in it: the viewpoint. */
.cd__view {
    margin: 0 0 var(--sp-4);
    color: var(--c-ink);
    font-weight: 500;
}

.cd__note {
    display: block;
    margin: 0;
}

/* The sheet holds its 320 : 380 box before the drawing paints. */
.cd__sheet {
    width: 100%;
    aspect-ratio: 32 / 38;
    overflow: hidden;
}

.cd__svg {
    display: block;
    width: 100%;
    height: auto;
}

.cd__line {
    fill: none;
    stroke-width: 1;
    stroke-linecap: square;
    stroke-linejoin: miter;
    vector-effect: non-scaling-stroke;
}

/* The new wheel: solid ink, the tyre tinted around the rim. */
.cd__new {
    stroke: var(--c-ink);
    stroke-width: 1.5;
}

.cd__ring {
    fill: var(--c-line-2);
    stroke: none;
}

/* The current wheel: dashed, a step back. */
.cd__old {
    stroke: var(--c-ink-3);
    stroke-dasharray: 4 3;
}

/* The mounting face the way a drawing office draws a datum: dash-dot. */
.cd__face {
    stroke: var(--c-ink-2);
    stroke-width: 1.5;
    stroke-dasharray: 6 3 1 3;
}

/* The car's schematic parts: a quiet outline, never mistaken for a wheel. */
.cd__schematic {
    stroke: var(--c-line-2);
    stroke-width: 1.25;
}

.cd__spring {
    stroke: var(--c-line-2);
    stroke-linejoin: round;
}

/* Arrows in the secondary ink, extension lines in the tertiary; nothing is blue, green or red. */
/* Flush ends: a square cap would draw every dimension half a stroke longer at each end — about
   2 mm on this scale — so the visible line would be longer than the number printed beside it. */
.cd__dim {
    stroke: var(--c-ink-2);
    stroke-linecap: butt;
}

.cd__head {
    fill: var(--c-ink-2);
    stroke: none;
}

.cd__ext {
    stroke: var(--c-ink-3);
    stroke-width: 0.75;
}

.cd__ext--old {
    stroke-dasharray: 2 2;
}

.cd__legend {
    display: flex;
    flex-wrap: wrap;
    gap: var(--sp-8) var(--sp-16);
    margin: var(--sp-4) 0 0;
}

.cd__key {
    display: inline-flex;
    align-items: center;
    gap: var(--sp-8);
    min-width: 0;
}

.cd__swatch {
    flex: none;
    overflow: visible;
}

.cd__caption {
    display: block;
    margin: 0;
}
</style>
